apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    capabilities: Basic Install
  name: knative-eventing-operator.v0.5.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: The Knative Eventing Installation
      displayName: Install
      kind: Install
      name: installs.eventing.knative.dev
      version: v1alpha1
    - description: The Knative Eventing AwsSqsSource
      displayName: AwsSqsSource
      kind: AwsSqsSource
      name: awssqssources.sources.eventing.knative.dev
      version: v1alpha1
    - description: The Knative Eventing ContainerSource
      displayName: ContainerSource
      kind: ContainerSource
      name: containersources.sources.eventing.knative.dev
      version: v1alpha1
    - description: The Knative Eventing CronJobSource
      displayName: CronJobSource
      kind: CronJobSource
      name: cronjobsources.sources.eventing.knative.dev
      version: v1alpha1
    - description: The Knative Eventing GitHubSource
      displayName: GitHubSource
      kind: GitHubSource
      name: githubsources.sources.eventing.knative.dev
      version: v1alpha1
    - description: The Knative Eventing KubernetesEventSource
      displayName: KubernetesEventSource
      kind: KubernetesEventSource
      name: kuberneteseventsources.sources.eventing.knative.dev
      version: v1alpha1
    - description: The Knative Eventing CamelSource
      displayName: CamelSource
      kind: CamelSource
      name: camelsources.sources.eventing.knative.dev
      version: v1alpha1
    - description: The Knative Eventing KafkaSource
      displayName: KafkaSource
      kind: KafkaSource
      name: kafkasources.sources.eventing.knative.dev
      version: v1alpha1
    - description: The Knative Eventing Broker
      displayName: Broker
      kind: Broker
      name: brokers.eventing.knative.dev
      version: v1alpha1
    - description: The Knative Eventing Channel
      displayName: Channel
      kind: Channel
      name: channels.eventing.knative.dev
      version: v1alpha1
    - description: The Knative Eventing ClusterChannelProvisioner
      displayName: ClusterChannelProvisioner
      kind: ClusterChannelProvisioner
      name: clusterchannelprovisioners.eventing.knative.dev
      version: v1alpha1
    - description: The Knative Eventing Subscription
      displayName: Subscription
      kind: Subscription
      name: subscriptions.eventing.knative.dev
      version: v1alpha1
    - description: The Knative Eventing Trigger
      displayName: Trigger
      kind: Trigger
      name: triggers.eventing.knative.dev
      version: v1alpha1
  description: Placeholder description
  displayName: Knative Eventing Operator
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - eventing.knative.dev
          resources:
          - triggers
          - triggers/status
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - ""
          resources:
          - namespaces
          - secrets
          - configmaps
          - services
          - events
          - serviceaccounts
          verbs:
          - get
          - list
          - create
          - update
          - delete
          - patch
          - watch
        - apiGroups:
          - networking.istio.io
          resources:
          - virtualservices
          verbs:
          - get
          - list
          - create
          - update
          - delete
          - patch
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - get
          - list
          - create
          - update
          - delete
          - patch
          - watch
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - rolebindings
          verbs:
          - get
          - list
          - create
          - update
          - delete
          - patch
          - watch
        - apiGroups:
          - eventing.knative.dev
          resources:
          - brokers
          - brokers/status
          - channels
          - channels/status
          - clusterchannelprovisioners
          - clusterchannelprovisioners/status
          - subscriptions
          - subscriptions/status
          - triggers
          - triggers/status
          verbs:
          - get
          - list
          - create
          - update
          - delete
          - patch
          - watch
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resources:
          - deployments
          - deployments/finalizers
          verbs:
          - get
          - list
          - create
          - update
          - delete
          - patch
          - watch
        - apiGroups:
          - admissionregistration.k8s.io
          resources:
          - mutatingwebhookconfigurations
          verbs:
          - get
          - list
          - create
          - update
          - delete
          - patch
          - watch
        - apiGroups:
          - eventing.knative.dev
          resources:
          - brokers
          - brokers/status
          - channels
          - channels/status
          - clusterchannelprovisioners
          - clusterchannelprovisioners/status
          - subscriptions
          - subscriptions/status
          - triggers
          - triggers/status
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - sources.eventing.knative.dev
          resources:
          - awssqssources
          - containersources
          - cronjobsources
          - githubsources
          - kuberneteseventsources
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - sources.eventing.knative.dev
          resources:
          - awssqssources/finalizers
          - containersources/finalizers
          - cronjobsources/finalizers
          - githubsources/finalizers
          - kuberneteseventsources/finalizers
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - sources.eventing.knative.dev
          resources:
          - awssqssources/status
          - containersources/status
          - cronjobsources/status
          - githubsources/status
          - kuberneteseventsources/status
          verbs:
          - get
          - update
          - patch
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - eventing.knative.dev
          resources:
          - channels
          - brokers
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - serving.knative.dev
          resources:
          - services
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - sources.eventing.knative.dev
          resources:
          - kafkasources
          - kafkasources/finalizers
          - services
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - sources.eventing.knative.dev
          resources:
          - kafkasources/status
          - services
          verbs:
          - get
          - update
          - patch
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - eventing.knative.dev
          resources:
          - channels
          - services
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - serving.knative.dev
          resources:
          - services
          - routes
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - sources.eventing.knative.dev
          resources:
          - camelsources
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - sources.eventing.knative.dev
          resources:
          - camelsources/status
          - camelsources/finalizers
          verbs:
          - get
          - update
          - patch
        - apiGroups:
          - serving.knative.dev
          resources:
          - services
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - eventing.knative.dev
          resources:
          - channels
          - brokers
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - camel.apache.org
          resources:
          - '*'
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - security.openshift.io
          resourceNames:
          - privileged
          - anyuid
          resources:
          - securitycontextconstraints
          verbs:
          - use
        - apiGroups:
          - extensions
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - build.knative.dev
          resources:
          - '*/finalizers'
          verbs:
          - update
        - apiGroups:
          - policy
          resources:
          - podsecuritypolicies
          verbs:
          - create
          - update
          - patch
          - get
        - apiGroups:
          - build.knative.dev
          resources:
          - '*'
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - get
          - create
          - update
          - delete
        serviceAccountName: knative-eventing-operator
      deployments:
      - name: knative-eventing-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: knative-eventing-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: knative-eventing-operator
            spec:
              containers:
              - command:
                - knative-eventing-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: knative-eventing-operator
                image: quay.io/openshift-knative/knative-eventing-operator:v0.5.0
                args:
                  - --olm
                  - --install
                  - --filename=https://raw.githubusercontent.com/openshift/knative-eventing/release-v0.5.0/openshift/release/knative-eventing-v0.5.0.yaml,https://raw.githubusercontent.com/openshift/knative-eventing-sources/release-v0.5.0/openshift/release/knative-eventing-sources-v0.5.0.yaml
                imagePullPolicy: Always
                name: knative-eventing-operator
                resources: {}
              serviceAccountName: knative-eventing-operator
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - knative-eventing-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - eventing.knative.dev
          resources:
          - '*'
          verbs:
          - '*'
        serviceAccountName: knative-eventing-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - serverless
  - eventing
  - camel
  - kafka
  maintainers:
  - email: mwessend@redhat.com
    name: Matthias Wessendorf
  maturity: alpha
  provider:
    name: Knative Community
  replaces: knative-eventing.v0.4.1
  version: 0.5.0
