---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: channels.eventing.knative.dev
  labels:
    knative.dev/crd-install: "true"
spec:
  group: eventing.knative.dev
  version: v1alpha1
  names:
    kind: Channel
    plural: channels
    singular: channel
    categories:
    - all
    - knative
    - eventing
    shortNames:
    - chan
  scope: Namespaced
  subresources:
    status: {}
  additionalPrinterColumns:
    - name: Ready
      type: string
      JSONPath: ".status.conditions[?(@.type==\"Ready\")].status"
    - name: Reason
      type: string
      JSONPath: ".status.conditions[?(@.type==\"Ready\")].reason"
    - name: Age
      type: date
      JSONPath: .metadata.creationTimestamp
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            provisioner:
              type: object
              required:
                - apiVersion
                - kind
                - name
              properties:
                apiVersion:
                  type: string
                  minLength: 1
                kind:
                  type: string
                  minLength: 1
                name:
                  type: string
                  minLength: 1
            arguments:
              type: object
            subscribable:
              type: object
              properties:
                subscribers:
                  type: array
                  items:
                    required:
                      - ref
                    properties:
                      ref:
                        type: object
                        required:
                          - namespace
                          - name
                          - uid
                        properties:
                          apiVersion:
                            type: string
                          kind:
                            type: string
                          name:
                            type: string
                            minLength: 1
                          namespace:
                            type: string
                            minLength: 1
                          uid:
                            type: string
                            minLength: 1
                      subscriberURI:
                        type: string
                        minLength: 1
                      replyURI:
                        type: string
                        minLength: 1
