---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: triggers.eventing.knative.dev
  labels:
    knative.dev/crd-install: "true"
spec:
  group: eventing.knative.dev
  version: v1alpha1
  names:
    kind: Trigger
    plural: triggers
    singular: trigger
    categories:
    - all
    - knative
    - eventing
  scope: Namespaced
  subresources:
    status: {}
  additionalPrinterColumns:
    - name: Ready
      type: string
      JSONPath: ".status.conditions[?(@.type==\"Ready\")].status"
    - name: Reason
      type: string
      JSONPath: ".status.conditions[?(@.type==\"Ready\")].reason"
    - name: Broker
      type: string
      JSONPath: .spec.broker
    - name: Subscriber_URI
      type: string
      JSONPath: .status.subscriberURI
    - name: Age
      type: date
      JSONPath: .metadata.creationTimestamp
  validation:
    openAPIV3Schema:
      properties:
        spec:
          required:
            - subscriber
          properties:
            broker:
              type: string
            filter:
              type: object
              properties:
                sourceAndType:
                  type: object
                  properties:
                    type:
                      type: string
                    source:
                      type: string
            subscriber:
              type: object
              properties:
                dnsName:
                  type: string
                  minLength: 1
                uri:
                  type: string
                  minLength: 1
                ref:
                  type: object
                  required:
                    - apiVersion
                    - kind
                    - name
                  properties:
                    apiVersion:
                      type: string
                      minLength: 1
                    kind:
                      type: string
                      minLength: 1
                    name:
                      type: string
                      minLength: 1
